In [2]:
class MyFirstClass:
    pass
    
a = MyFirstClass()

In [3]:
b = MyFirstClass()

In [4]:
print(a)

In [5]:
print(b)

In [7]:
class Point:
    pass

In [8]:
p1=Point()
p2=Point()

In [11]:
p1.x=5
p2.y=6
p1.y=5
p2.x=6

In [12]:
print(p1.x,p1.y)
print(p2.x,p2.y)

5 5
6 6


In [13]:
class Point:
    def reset(self):
        self.x=0
        self.y=0
        
p = Point()
p.reset()
print(p.x,p.y)

0 0


In [16]:
class Point:
    def reset(self):
        pass
        
p = Point()
p.reset()


In [17]:
import math
class Point:
    def move(self,x,y):
        self.x = x
        self.y = y
    def reset(self):
        self.move(0,0)
    def calculate_distance(self,other_point):
        return math.sqrt((self.x - other_point.x)**2 + (self.y - other_point.y)**2)
    

In [19]:
point1 = Point()
point2 = Point()
point1.reset()
point2.move(5,0)
print(point2.calculate_distance(point1))

5.0


In [1]:
assert (point2.calculate_distance(point1) == point1.calculate(point2))
point1.move(3,4)
print(print)

NameError: name 'point2' is not defined

In [2]:
import torch

In [6]:
torch

<module 'torch' from '/Applications/anaconda3/lib/python3.7/site-packages/torch/__init__.py'>

In [7]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
z = x.add(y)
print(z)
print(x)
x.add_(x)
print(x)

tensor([4, 6])
tensor([1, 2])
tensor([2, 4])


In [9]:
torch.Tensor([1,2,3,4,5,6])
torch.Tensor(2,3)
t = torch.Tensor([[1,2,3],[4,5,6]])
t.size()

torch.Size([2, 3])

In [10]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
t.shape

torch.Size([2, 3])

In [13]:
torch.Tensor(t.size())

tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [4.1586e-05, 2.7301e-06, 1.2973e-11]])

In [14]:
t1 = torch.Tensor(1)
t2 = torch.tensor(1)
print("t1的值{},t1的数据类型{},".format(t1,t1.type()))

t1的值tensor([0.]),t1的数据类型torch.FloatTensor,


In [15]:
print("t2的值{},t2的数据类型{},".format(t2,t2.type()))

t2的值1,t2的数据类型torch.LongTensor,


In [16]:
torch.eye(2,2)
torch.zeros(2,3)
torch.linspace(1,10,4)
torch.rand(2,3)
torch.randn(2,3)
torch.zeros_like(torch.rand(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [18]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [20]:
torch.rand(2,3)

tensor([[0.4006, 0.8052, 0.4741],
        [0.8227, 0.1075, 0.4625]])

In [21]:
torch.randn(2,3)

tensor([[-1.2040,  0.3448, -1.4764],
        [-0.1060,  0.0380,  0.8287]])

In [22]:
torch.zeros_like(torch.rand(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
x = torch.randn(2,3)
x.size()

torch.Size([2, 3])

In [24]:
x.dim()

2

In [26]:
x.view(3,2)

tensor([[ 0.5315, -0.6744],
        [-0.2450,  1.6836],
        [ 2.2063, -0.0402]])

In [27]:
y.shape

torch.Size([2])

In [32]:
y = x.view(-1)
z = torch.unsqueeze(y,0)
z.size()

torch.Size([1, 6])

In [29]:
z

tensor([[3, 4]])

In [30]:
y

tensor([3, 4])

In [31]:
z.size()

torch.Size([1, 2])

In [33]:
y

tensor([ 0.5315, -0.6744, -0.2450,  1.6836,  2.2063, -0.0402])

In [34]:
y.size()

torch.Size([6])

In [35]:
z

tensor([[ 0.5315, -0.6744, -0.2450,  1.6836,  2.2063, -0.0402]])

In [36]:
z.numel()

6

In [37]:
index_select(input,dim,index)

NameError: name 'index_select' is not defined

In [40]:
torch.manual_seed(100)
x = torch.randn(2,3)
x[:,-1]
mask = x > 0


tensor([-0.3938, -2.3134])

In [41]:
mask = x > 0

In [42]:
torch.nonzero(mask)

tensor([[0, 0],
        [1, 0]])

In [43]:
torch.masked_select(x,mask)

tensor([0.3607, 0.2429])